### ISSUE TITLE
flow

### ISSUE THREAD

**Issue by harry-promogata** [rizkiandrianto/script-mutasi-bca#1]
hi mas rizki..
ini sistem kerjanya (not how to install) bgaimana mas?
diambil lngsung dri bank bca, lalu disimpan ke database?
ngisi no rekening & password banknya di mana?

thx

**Comment by rizkiandrianto** [comment]
Halo mas harry,

Sejujurnya saya beli script ini dan belum saya pakai sampai sekarang, belum sempat instalasi & karena saya gamau pakai software bawaan dia.
Agak was2 hehe.

Tapi saya pernah bongkar, scriptnya cara kerjanya cuma nge-curl web mobile banking bca, lalu disimpan ke cookies, untuk selanjutnya curl halaman selanjutnya (karena kalau ga ada cookies halaman selanjutnya nolak).

Untuk username & password ada di ibparser, fungsi login() ada $username & $password.

Salam.
